name: Link DHIS2 Jira issues
on:
  pull_request:
    types: 
    - opened
    - reopened
    - edited
    - synchronize
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Link DHIS2 Jira issues
      uses: ./