name: Link DHIS2 Jira issues
on:
  pull_request:
    types: 
    - opened
    - reopened
    - edited
    - synchronize
  issue_comment:
    types:
    - edited

permissions:
  contents: read
  pull-requests: write

jobs:
  check:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Link DHIS2 Jira issues
      uses: ./
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}